import type { Metadata } from "next";
import "./globals.css";

import { Poppins, Josefin_Sans, Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "./utils/theme-provider";

// --- Fonts
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// --- Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// --- Root Layout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} ${josefinSans.variable}`}>
        {/* ThemeProvider is a Client Component */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* Client-side container for theme + fonts */}
          <div className="bg-white dark:bg-black text-black dark:text-white min-h-screen transition-colors duration-300">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
